name: format check

on:
  push:
    branches: main
    paths:
      - '**.py'

  pull_request:
    branches: main
    paths:
      - '**.py'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-format-check
  cancel-in-progress: true

jobs:
  format-lint-code-check:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.5.0

      - name: Install deps
        run: python3 -m pip install pylint black

      - name: Check code Formatting and Linting
        run: pylint oneliner.py

