name: Check format

on:
  push:
    branches: master

  pull_request:
    branches: master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-format-check
  #cancel-in-progress: true

jobs:
  format-check:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.5.0

      - name: Install deps
        run: python3 -m pip install pylint black

      - name: Check code Formatting and Linting
        run: black --check ./
        #pylint oneliner.py
