name: run unitest

on:
  push:
    branches: master

  pull_request:
    branches: master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-unitest
  #cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3.5.0
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Run tests
        run: python3 ./oneliner_unitest.py
